### ISSUE TITLE
which data set u use ? for training

### ISSUE THREAD

**Issue by xeron56** [MenghanXia/InverseHalftoning#2]
`python3 main.py
Running PRLNet -Training!
Traceback (most recent call last):
  File "main.py", line 244, in <module>
    train(train_list, val_list, debug_mode=True)
  File "main.py", line 44, in train
    input_imgs, target_imgs, num = input_producer(train_list, in_channels, batch_size, need_shuffle=True)
  File "/content/drive/My Drive/InverseHalftoning/model.py", line 76, in input_producer
    raise Exception("empty data list!")
Exception: empty data list!`
![fsfd](https://user-images.githubusercontent.com/11449967/66248958-0abb7200-e74f-11e9-8d78-04d9b330e4e3.PNG)

**Comment by ajnasmuhammed89** [comment]
Same is happening with me... can you tell me what exactly the problem is?
